// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjnwekfnrjcnyvamlput.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhqbndla2Zucmpjbnl2YW1scHV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMTE0MDYsImV4cCI6MjA2OTY4NzQwNn0.i79LNnOvFuZTUEs_0mPZS7IQ2ofjJou3vKt_rvM_HTk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});